version: "3.4"
services:
  victim:
    image: victim
    build:
      context: ./victim
    networks:
      - hacknet
    entrypoint: ["tail", "-f", "/dev/null"]
  spoofer:
    image: spoofer
    build:
      context: ./spoofer
    networks:
      - hacknet
    entrypoint: ["tail", "-f", "/dev/null"]
    privileged: true
  # hids:
  #   # image: atomicorp/ossec-docker
  #   build:
  #     context: ./ossec-docker
  #   networks:
  #     - hacknet
  #   # entrypoint: ["tail", "-f", "/dev/null"]
  #   # volumes:
  #   #   - hids-config:/var/ossec/
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
networks:
  hacknet:
    driver: bridge
    # attachable: true
volumes:
  hids-config:
